/**
 * Hardcoded fallback / seed for Series + Variant.
 *
 * This file is the source of truth for both:
 *   - the `npm run seed` script (one-time Mongo upsert per variant slug)
 *   - the public render fallback when Mongo is unreachable, so builds never
 *     break before the CMS is configured.
 *
 * Editing content here is OPTIONAL once a variant is in Mongo — the CMS at
 * /admin/products/[id] is the live source of truth. Re-seeding will NOT
 * overwrite Mongo entries that already exist (the seed script does an
 * upsert-if-missing).
 *
 * To add a brand-new model:
 *   1. Add the series entry below if missing.
 *   2. Add a variant entry with the page's data.
 *   3. Run `npm run seed`.
 *   4. Replace the page's .astro file with a wrapper that imports
 *      <VariantPage> and calls loadVariantBySlug('your-slug').
 */

import type { VariantDoc } from '../db/models/Variant';

export interface SeriesSeed {
  slug: string;
  name: string;
  accentColor: string;
  order: number;
}

// Strip Mongo-specific fields for the public render path; keep the rest 1:1
export type VariantSeed = Omit<VariantDoc, '_id' | 'seriesId' | 'createdAt' | 'updatedAt'> & {
  seriesSlug: string;
};

export const SERIES_SEED: SeriesSeed[] = [
  { slug: 'grand-rover', name: 'Grand Rover', accentColor: '#E50000', order: 1 },
  { slug: 'wild-drifter', name: 'Wild Drifter', accentColor: '#E50000', order: 2 },
  { slug: 'tanzanite', name: 'Tanzanite', accentColor: '#E50000', order: 3 },
  { slug: 'amore', name: 'Amore', accentColor: '#E50000', order: 4 },
  { slug: 'atom', name: 'Atom', accentColor: '#E50000', order: 5 },
  { slug: 'huttle', name: 'Hütte', accentColor: '#E50000', order: 6 },
  { slug: 'armadillo', name: 'Armadillo', accentColor: '#D4AF37', order: 7 },
  { slug: 'eco', name: 'Eco', accentColor: '#E50000', order: 8 },
];

const SPEC_TABLE_EMPTY = {
  ultra:   { chassis: [], furniture: [], electrical: [], plumbing: [] },
  terrain: { chassis: [], furniture: [], electrical: [], plumbing: [] },
  hiker:   { chassis: [], furniture: [], electrical: [], plumbing: [] },
} as const;

// Shared Hike RV pack spec across Grand Rover variants — reused for the 20.6 /
// 21.6 / Infinity since they ship the same Ultra/Terrain/Hiker option packs.
const GRAND_ROVER_SPEC_TABLE = {
  ultra: {
    chassis: ['New style chassis', 'Extended 2200mm A-frame', '3.5T Tuffride Stage 3 Airbag suspension', 'DO-35 hitch', '265/75/R16 tyres', 'Black Jack-Master jockey wheel', '2× 105L fresh water tanks', '1× 105L grey water tank', '50L drinking water tank', 'Stoneguard', 'Large twin-slide universal toolbox', 'Bumper bar with woodbox & jerry', 'Composite panels cladding', 'Plain Raven sheet 800mm bottom', 'XPS insulation', 'Manual double pullout step', 'Recessed picnic table with shelves', 'Carefree Electric awning', 'Sahara Caravan dust reduction'],
    furniture: ['Lightweight cabinetry', 'Waterfall benchtop', 'Full aluminium frame shell', 'Cortina Hex sliding door', 'External TV box', '3× LED strips in overhead cupboards', 'Softclose draw runners', 'Mirrored shower perspex', 'Telescopic table', 'Aussie Traveller EV2 windows', 'Double bedroom windows', '2 headrests', 'Lounge padding', 'Round mag pocket', 'Recessed footrest'],
    electrical: ['14" LED bar light (front & back)', '1× 14" bar light each side (work lights)', 'Victron Off-Grid Multi-3000 BMS', '2× 300Ah Lithium batteries', '5× 200W solar panels', 'Portable solar', 'Step strip light', 'Fusion MSRA60 kit stereo', '2× 12V fans in bedroom'],
    plumbing: ['Dometic 224L Compressor fridge', '29L NCE 4-in-1 microwave', 'Camec 2.3kW induction cooktop', 'Suburban Instant HWS + water-saving valve', 'OGO Compost toilet', 'Hot & cold taps near bayonet', 'AU Focus diesel heater', '3.2kg top-load washing machine', 'External shower'],
  },
  terrain: {
    chassis: ['Standard chassis', 'Extended 1900mm A-frame', '3.3T Tuffride Independent suspension', 'DO-35 hitch', '245/75/R16 tyres', 'Top Winder 8" jockey wheel', '2× 105L fresh water tanks', '1× 105L grey water tank', 'Medium twin-slide toolbox', 'Standard 3-arm rear bumper', 'Composite panels cladding', 'Checkerplate 600mm bottom', 'Polystyrene insulation', 'Manual single pullout step', 'Standard picnic table', 'ATRV rollout awning'],
    furniture: ['Standard cabinetry', 'Waterfall benchtop', 'Hybrid AL-frame + rot-free shell', 'Standard sliding door', 'Softclose draw runners', 'Frosted shower perspex', 'Telescopic table', 'SJ RV flat acrylic windows', 'Lounge padding', 'Square mag pocket'],
    electrical: ['LED Annex light (front & back)', 'Projecta PM335C + 4" display BMS', '2× 150Ah Lithium batteries', '2× 200W solar panels', 'ATRV stereo'],
    plumbing: ['Dometic 188L Compressor fridge', '20L NCE microwave', 'Swift Mini Grill cooker', 'Swift 28L HWS', 'Thetford cassette toilet', '3.2kg top-load washing machine', 'External shower'],
  },
  hiker: {
    chassis: ['Standard chassis', 'Standard 1650mm A-frame', '3.2T Roller Rocker suspension', '50mm ball hitch', '235/75/R15 tyres', 'Top Winder 8" jockey wheel', '2× 105L fresh water tanks', 'Standard 3-arm rear bumper', 'Corrugated panels cladding', 'Checkerplate 300mm bottom', 'Polystyrene insulation', 'Manual single pullout step', 'Standard picnic table', 'ATRV rollout awning'],
    furniture: ['Standard cabinetry', 'Meranti Timber shell', 'Standard sliding door', 'Standard draw runners', 'Frosted shower perspex', 'Standard table', 'SJ RV flat acrylic windows', 'Square mag pocket'],
    electrical: ['Projecta PM335C + 4" display BMS', '1× 150Ah Lithium battery', '2× 200W solar panels', 'ATRV stereo'],
    plumbing: ['Dometic 188L 3-way fridge', '20L NCE microwave', 'Swift Mini Grill cooker', 'Swift 28L HWS', 'Thetford cassette toilet'],
  },
};

export const VARIANT_SEED: VariantSeed[] = [
  // ── GRAND ROVER ──────────────────────────────────────────────
  {
    seriesSlug: 'grand-rover',
    slug: 'grand-rover-196',
    name: 'Grand Rover 19.6',
    status: 'published',
    order: 1,
    hero: {
      kicker: 'Model 19.6ft · 2 Bunk',
      title: 'Family.',
      subtitle: 'Grand Rover 19.6ft',
      body: 'The compact Grand Rover, sized for easier towing and tighter sites — without losing the bunk beds, ensuite, or kitchen the family relies on.',
      heroImage: '/assets/GRANDROVER 19.6.jpg',
      brochureUrl: '/brochures/GRANDROVER.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'L-Lounge Convertible' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: '3kg Front-load', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '5 × 210W', caption: 'Solar Panel' },
    ],
    specTable: GRAND_ROVER_SPEC_TABLE,
    premiumLiving: {
      heading: 'Family-First Layout.',
      body: 'Two dedicated bunks for the kids, an island queen for the parents, and a swing-around dinette that converts to extra sleeping when needed — the 19.6 carries four (or five) without ever feeling cramped. The full kitchen runs a 188-litre fridge, recessed mini-grill, microwave, and proper benchtop space. The fully separate shower and toilet keeps the morning routine flowing — and the L-shape lounge is the after-dark headquarters when the kids are down.',
      images: [
        '/rover/grandrover/19.6 Family First/1.jpg',
        '/rover/grandrover/19.6 Family First/2.jpg',
        '/rover/grandrover/19.6 Family First/3.jpg',
      ],
      chips: ['Bunk beds', 'Full ensuite', 'L-Lounge', 'Front kitchen'],
    },
    floorplans: [
      { title: 'Grand Rover 19.6 · 2 Bunk', desc: 'Family-Ready Floorplan', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GRAND ROVER 19.6 2 BUNK.png' },
    ],
    cta: {
      kicker: 'Your Family Adventure Starts Here',
      heading: 'Ready For The Grand Rover 19.6?',
      body: 'Contact our team to configure your Grand Rover 19.6 for your next adventure.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: true,
    backLinkHref: '/grand-rover',
    backLinkLabel: 'Grand Rover Series',
  },
  {
    seriesSlug: 'grand-rover',
    slug: 'grand-rover-206',
    name: 'Grand Rover 20.6',
    status: 'published',
    order: 2,
    hero: {
      kicker: 'Model 20.6',
      title: 'Built.',
      subtitle: 'Grand Rover 20.6ft',
      body: 'Built for the long haul with a strong frame, proven features, and a design that handles highway and outback.',
      heroImage: '/rover/grandrover/Grand Rover 20.6.png',
      brochureUrl: '/brochures/GRANDROVER.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'L-Lounge Convertible' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: '3kg Front-load', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '5 × 210W', caption: 'Solar Panel' },
    ],
    specTable: GRAND_ROVER_SPEC_TABLE,
    premiumLiving: {
      heading: 'Thoughtfully Designed.',
      body: 'Enjoy a thoughtfully designed lounge with a swing-around table, overhead cabinetry, and generous windows that flood the interior with natural light. Storage is optimised without compromising floor space. The full kitchen offers a recessed mini grill, microwave, benchtops, and quality cabinetry. The ensuite features a separate shower and toilet, giving real privacy on the road and making long touring easy and comfortable.',
      images: [
        '/rover/grandrover/20.6/interior1.png',
        '/rover/grandrover/20.6/interior2.png',
        '/rover/grandrover/20.6/interior3.png',
      ],
      chips: [],
    },
    floorplans: [
      { title: 'Grand Rover 20.6', desc: 'Optimised Family Living', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GRAND ROVER 19.6 2 BUNK.png' },
    ],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Ready For The 20.6ft?',
      body: 'Contact our team to configure the perfect Grand Rover 20.6 for your touring lifestyle.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: true,
    backLinkHref: '/grand-rover',
    backLinkLabel: 'Grand Rover Series',
  },
  {
    seriesSlug: 'grand-rover',
    slug: 'grand-rover-216',
    name: 'Grand Rover 21.6',
    status: 'published',
    order: 3,
    hero: {
      kicker: 'Model 21.6',
      title: 'Stylish.',
      subtitle: 'Grand Rover 21.6ft',
      body: 'The 21.6 version combines thoughtful layout with high-end finishes for a travelling home that feels luxurious.',
      heroImage: '/rover/grandrover/Grand Rover 21.6.png',
      brochureUrl: '/brochures/GRANDROVER.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'L-Lounge Convertible' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: '3kg Front-load', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '5 × 210W', caption: 'Solar Panel' },
    ],
    specTable: GRAND_ROVER_SPEC_TABLE,
    premiumLiving: {
      heading: 'Interiors With Exceptional Design.',
      body: 'The interior of the Grand Rover 21.6 exudes warmth and sophistication. Quality upholstery, ambient lighting, and refined cabinetry make relaxing inside feel effortless. Every surface, finish and fixture is chosen to elevate your living experience. Large windows flood light and allow views, while smart ventilation ensures air flow. Space flows seamlessly between the living, dining, bathroom, and sleeping zones, giving you a homey feel without compromising on functionality.',
      images: [
        '/rover/grandrover/21.6/interior1.png',
        '/rover/grandrover/21.6/interior2.png',
        '/rover/grandrover/21.6/interior3.png',
      ],
      chips: [],
    },
    floorplans: [
      { title: 'Grand Rover 21.6 v1', desc: 'Front Bedroom + Rear Lounge', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GRAND ROVER 21.6 v1.0.png' },
      { title: 'Grand Rover 21.6 v2', desc: 'Alternate Family Configuration', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GRAND ROVER 21.6 v2.0.png' },
      { title: 'Grand Rover 21.6 v3', desc: 'Bunk + Lounge Variant', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GRAND ROVER 21.6 v3.0.png' },
    ],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Ready For The 21.6ft?',
      body: "Contact our team to discuss the Grand Rover 21.6 and configure the perfect setup for your family's touring lifestyle.",
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: true,
    backLinkHref: '/grand-rover',
    backLinkLabel: 'Grand Rover Series',
  },
  {
    seriesSlug: 'grand-rover',
    slug: 'grand-rover-infinity',
    name: 'Grand Rover Infinity',
    status: 'published',
    order: 4,
    hero: {
      kicker: 'Flagship Model',
      title: 'Spacious.',
      subtitle: 'Grand Rover Infinity',
      body: 'Crafted with precision, the Grand Rover Infinity is the epitome of luxury and durability, designed for families seeking unparalleled adventure.',
      heroImage: '/rover/grandrover/Grand Rover Infinity.png',
      brochureUrl: '/brochures/GRANDROVER.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'L-Lounge Convertible' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: '3kg Front-load', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '5 × 210W', caption: 'Solar Panel' },
    ],
    specTable: GRAND_ROVER_SPEC_TABLE,
    premiumLiving: {
      heading: 'Fully Equipped For Adventure.',
      body: 'With a silver-shine 6″ chassis, 2″ chassis raiser, extended A-frame, drop step, and 3500kg 10″ brakes, the Grand Rover Infinity is engineered for durability and performance on all terrains. The interior boasts leatherette upholstery, soft-close drawers, and a Nuova Mapa table. Enjoy cooking with a recessed mini grill, microwave, and white ceramic sink with drainer. The ensuite features a white ceramic basin and Thetford cassette toilet. Separate shower and toilet compartments ensure privacy and practicality on extended journeys.',
      images: [
        '/rover/grandrover/Infinity Equipped/1.jpg',
        '/rover/grandrover/Infinity Equipped/2.jpg',
        '/rover/grandrover/Infinity Equipped/3.jpg',
      ],
      chips: [],
    },
    floorplans: [
      { title: 'Grand Rover Infinity 23.6', desc: 'The Flagship Floorplan', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GRAND ROVER 23.6 INFINITY.png' },
      { title: 'Grand Rover Infinity 24.6', desc: 'Extended Luxury Variant', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GRAND ROVER 24.6 INFINITY.png' },
    ],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Choose Infinity.',
      body: 'Contact our team to configure the Grand Rover Infinity — the flagship of family touring.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: true,
    backLinkHref: '/grand-rover',
    backLinkLabel: 'Grand Rover Series',
  },

  // ── WILD DRIFTER ─────────────────────────────────────────────
  {
    seriesSlug: 'wild-drifter',
    slug: 'wild-drifter-196',
    name: 'Wild Drifter 19.6',
    status: 'published',
    order: 1,
    hero: {
      kicker: 'Model 19.6',
      title: 'Adventure.',
      subtitle: 'Wild Drifter 19.6ft',
      body: 'Explore the wild in comfort and style with the rugged Wild Drifter 19.6 caravan, built for all terrains.',
      heroImage: '/Wild Drifter/Images/External/Copy of IMG_4177.JPG',
      brochureUrl: '/brochures/WILD DRIFTER.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'Cafe Lounge' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: '3.2kg Top-load', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '5 × 210W', caption: 'Solar Panel' },
    ],
    specTable: {
      ultra: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Step', 'DO-35 Coupling'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'Postform Benchtops', 'Recessed Mini grill', 'Air conditioner Frame', 'Smoke detector'],
        electrical: ['LED Internal Down lights', 'LED Boot Lights', 'External 240 Power point', 'HV Wingard sensor', 'Grey Anderson Plug', '12 Pin Trailer Plug'],
        plumbing: ['Water fillers X 2 Lockable', '224L DOMETIC 3 way Fridge', 'Fridge/Freezer', 'Swift Mini grill', 'Water filter system', 'Thetford Cassette Toilet'],
      },
      terrain: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Step', 'Do-35 Coupling'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'Postform Benchtops', 'Recessed Mini grill', 'Smoke detector', 'Bottom Mount Rangehood'],
        electrical: ['3500 Gree air conditioner', '3 x Annex lights', 'LED Boot Lights', 'Tv Antenna', 'Bottom mount Rangehood', 'BM-pro Trail safe'],
        plumbing: ['Water fillers X 2 Lockable', 'Swift Mini grill', 'Water filter system', 'Flick Mixer Taps', 'Stainless steel sink', 'White Ceramic Basin'],
      },
      hiker: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" A-frame', 'Roller rocker suspension', '3 Arm Bumper Bar'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'Postform Benchtops', 'Recessed Mini grill', '20L Microwave', 'Smoke detector'],
        electrical: ['Gree 3500 air conditioner', 'Annex lights x 2', 'LED Boot Lights', 'External 240 Power point', 'Tv Antenna', 'BM-pro Trail safe'],
        plumbing: ['Water filter system', 'Thetford Cassette Toilet', 'Flick Mixer Taps', 'Swift 28L HWS Gas+ Elec', 'White Ceramic Basin', 'Tap on A-frame'],
      },
    },
    premiumLiving: {
      heading: 'Premium Living On Wheels.',
      body: 'Relax in the plush lounge or in soft innerspring comfort in your bed. Ambient lighting, ventilation, and neat storage zones create a space that invites rest and recuperation. Your ensuite includes a compact shower, vanity, and cassette toilet, which offers privacy and convenience in a small footprint. The finish quality and careful layout ensure that your comfort is never an afterthought.',
      images: [
        '/Wild Drifter/Images/Premium Living/1.jpg',
        '/Wild Drifter/Images/Premium Living/2.jpg',
        '/Wild Drifter/Images/Premium Living/3.jpg',
      ],
      chips: ['Plush Lounge', 'Innerspring Bed', 'Ambient Lighting', 'Compact Ensuite'],
    },
    floorplans: [
      { title: 'Wild Drifter 19.6', desc: 'The Ultimate Family Fiesta', src: '/Wild Drifter/Layouts Wild Drifter/3D-Layout-WILD-DRIFTER-19.6.jpg' },
    ],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Ready For The 19.6ft?',
      body: 'Contact our team to configure the perfect Wild Drifter 19.6 for your touring lifestyle.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: true,
    backLinkHref: '/wild-drifter',
    backLinkLabel: 'Wild Drifter Series',
  },
  {
    seriesSlug: 'wild-drifter',
    slug: 'wild-drifter-206',
    name: 'Wild Drifter 20.6',
    status: 'published',
    order: 2,
    hero: {
      kicker: 'Model 20.6',
      title: 'Rugged.',
      subtitle: 'Wild Drifter 20.6ft',
      body: 'Strong chassis and refined finishes make the 20.6 your perfect partner in remote and refined journeys.',
      heroImage: '/Wild Drifter/Images/External/Copy of IMG-20250402-WA0082.jpg',
      brochureUrl: '/brochures/WILD DRIFTER.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'Cafe Lounge' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: '3.2kg Top-load', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '5 × 210W', caption: 'Solar Panel' },
    ],
    specTable: {
      ultra: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Legs x 4', '2 X Battery Boxes'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'Postform Benchtops', 'Recessed Mini grill', 'Air conditioner Frame', 'Smoke detector'],
        electrical: ['LED Internal Down lights', 'LED Boot Lights', 'External 240 Power point', 'HV Wingard sensor', 'Grey Anderson Plug', '12 Pin Trailer Plug'],
        plumbing: ['Water fillers X 2 Lockable', '224L DOMETIC 3 way Fridge', 'Fridge/Freezer', 'Swift Mini grill', 'Water filter system', 'Thetford Cassette Toilet'],
      },
      terrain: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Step', 'Do-35 Coupling'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'Postform Benchtops', 'Queen Bed 1900 x 500mm', 'Smoke detector', 'Bottom Mount Rangehood'],
        electrical: ['Belair 3400 air conditioner', 'LED Internal Down lights', 'LED Boot Lights', 'External 240 Power point', 'Bottom mount Rangehood', 'BM-pro Trail safe'],
        plumbing: ['Water fillers X 2 Lockable', '188L DOMETIC 3 way', 'Fridge/Freezer', 'Swift Mini grill', '1 x Elec + 3 x gas', 'White Ceramic Basin'],
      },
      hiker: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', '2800KG 12" Brakes', '8" Jockey Wheels'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'Postform Benchtops', 'Recessed Mini grill', '20L Microwave', 'Smoke detector'],
        electrical: ['Belair 3400 air conditioner', 'LED Internal Down lights', 'LED Boot Lights', 'External 240 Power point', 'BM-pro Trail safe', 'Grey Anderson Plug'],
        plumbing: ['Water fillers X 2 Lockable', '188L DOMETIC 12v', 'Fridge/Freezer', 'Swift Mini grill', '1 x Elec + 3 x gas', 'Water filter system'],
      },
    },
    premiumLiving: {
      heading: "Comfort You'll Love Forever.",
      body: "Relax in its plush lounge with ambient lighting and well-planned windows. Rollover seating becomes a comfortable lounge or dining space; perfect for downtime and evenings. Sleep peacefully in the queen bed, enjoy the bathroom's compact design with a shower and vanity. Every surface is made to feel premium and durable, so your comfort never feels compromised.",
      images: [
        '/Wild Drifter/Images/Internal 4/Copy of IMG-20250402-WA0064.jpg',
        '/Wild Drifter/Images/Internal 4/Copy of IMG-20250402-WA0058.jpg',
        '/Wild Drifter/Images/Comfort/washer.jpg',
      ],
      chips: ['Plush Lounge', 'Queen Bed', 'Ambient Lighting', 'Shower & Vanity'],
    },
    floorplans: [
      { title: 'Wild Drifter 20.6', desc: 'Spacious Premium Oasis', src: '/Wild Drifter/Layouts Wild Drifter/3D-Layout-WILD-DRIFTER-20.6.jpg' },
    ],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Ready For The 20.6ft?',
      body: 'Contact our team to configure the perfect Wild Drifter 20.6 for your touring lifestyle.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: true,
    backLinkHref: '/wild-drifter',
    backLinkLabel: 'Wild Drifter Series',
  },

  // ── TANZANITE ────────────────────────────────────────────────
  {
    seriesSlug: 'tanzanite',
    slug: 'tanzanite-21',
    name: 'Tanzanite 21',
    status: 'published',
    order: 1,
    hero: {
      kicker: 'Model 21',
      title: 'Sturdy.',
      subtitle: 'Tanzanite 21ft',
      body: 'Step into refined living on the road with spacious layouts, premium finishes, and smart features.',
      heroImage: '/Tanzanite/Images/External/Copy of IMG-20250402-WA0091.jpg',
      brochureUrl: '/brochures/TANZANITE.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'Cafe Lounge' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: '3.2kg Top-load', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '5 × 210W', caption: 'Solar Panel' },
    ],
    specTable: {
      ultra: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Legs x 4', '2 X Battery Boxes'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'postform Benchtops', 'Recessed Mini grill', 'Air conditioner Frame', 'smoke detector'],
        electrical: ['Led Internal Down lights', 'Led Boot Lights', 'External 240 Power point', 'HV Wingard sensor', 'Grey Anderson Plug', '12 Pin Trailer Plug'],
        plumbing: ['Water fillers X 2 Lockable', '224L DOMETIC 3 way Fridge', 'Fridge/Freezer', 'Swift Mini grill', 'Water filter system', 'Thetford Cassette Toilet'],
      },
      terrain: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Step', 'Do-35 Coupling'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'postform Benchtops', 'Queen Bed 1900 x 500mm bed', 'smoke detector', 'Bottom MountRangehood'],
        electrical: ['3500 Gree air conditioner', 'Led Internal Down lights', 'Led Boot Lights', 'Bottom mount Rangehood', 'BM-pro Trail safe', 'Grey Anderson Plug'],
        plumbing: ['Water fillers X 2 Lockable', '188L DOMETIC 3 way', 'Fridge/Freezer', 'Swift Mini grill', '1 x Elec + 3 x gas', 'White Ceramic Basin'],
      },
      hiker: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" A-frame', '3 Arm Bumber Bar', '8" Jockey Wheels'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'postform Benchtops', 'Recessed Mini grill', '20L Microwave', 'smoke detector'],
        electrical: ['Gree 3500 air conditioner', 'Annex lights x 2', 'Led Boot Lights', 'External 240 Power point', 'BM-pro Trail safe', 'Grey Anderson Plug'],
        plumbing: ['Water fillers X 2 Lockable', '188L DOMETIC 12v', 'Fridge/Freezer', 'Swift Mini grill', '1 x Elec + 3 x gas', 'Water filter system'],
      },
    },
    premiumLiving: {
      heading: 'Interiors That Inspire Joy.',
      body: 'Every interior detail is crafted to delight your senses: soft lighting, quality upholstery, intelligent storage, and seamless finishes. The space feels open, warm, and refined, relaxing at every turn. Large, glazed windows let in natural light, while good ventilation keeps the environment fresh. The layout flows effortlessly between living, sleeping, dining, and ensuite zones so you never feel cramped or compromised.',
      images: ['/Tanzanite/Images/Inspire Joy/1.jpg', '/Tanzanite/Images/Inspire Joy/2.jpg', '/Tanzanite/Images/Inspire Joy/3.jpg'],
      chips: ['Soft Lighting', 'Seamless Finishes', 'Glazed Windows', 'Fresh Ventilation'],
    },
    floorplans: [
      { title: 'Tanzanite 21', desc: 'Grand Touring Excellence', src: '/3D LAYOUTS 2024/TANZANITE 21FT.jpg' },
    ],
    cta: {
      kicker: 'Touring Redefined',
      heading: 'Ready For The Tanzanite 21?',
      body: 'Contact our team to configure the perfect Tanzanite 21 for your touring lifestyle.',
    },
    gallery: {
      exterior: [
        '/Tanzanite/Images/External/Copy of IMG-20250402-WA0090.jpg',
        '/Tanzanite/Images/External/Copy of IMG-20250402-WA0091.jpg',
        '/Tanzanite/Images/External/Copy of IMG-20250402-WA0092.jpg',
        '/Tanzanite/Images/External/Copy of IMG-20250402-WA0093.jpg',
        '/Tanzanite/Images/External/Copy of IMG-20250402-WA0094.jpg',
        '/Tanzanite/Images/External/Copy of IMG-20250402-WA0095.jpg',
        '/Tanzanite/Images/External/Copy of IMG-20250402-WA0096.jpg',
        '/Tanzanite/Images/External/Copy of IMG-20250402-WA0099.jpg',
        '/Tanzanite/Images/External/Copy of IMG-20250402-WA0103.jpg',
      ],
      interior: [
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0088.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0089.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0097.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0098.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0100.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0101.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0102.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0104.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0105.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0106.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0114.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0115.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0116.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0117.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0118.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0119.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0120.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0121.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0122.jpg',
        '/Tanzanite/Images/Internal 2/Copy of IMG-20250402-WA0123.jpg',
        '/Tanzanite/Images/Internal 2/WhatsApp Image 2025-04-02 at 06.24.00_74a17024.jpg',
      ],
    },
    showMoodBoard: true,
    backLinkHref: '/drifter',
    backLinkLabel: 'Drifter Series',
  },

  // ── AMORE ────────────────────────────────────────────────────
  {
    seriesSlug: 'amore',
    slug: 'amore-22',
    name: 'Amore 22',
    status: 'published',
    order: 1,
    hero: {
      kicker: 'Model 22',
      title: 'Spacious.',
      subtitle: 'Amore 22ft',
      body: 'Make every getaway extraordinary in a spacious, innovative Amore 22 caravan. Comfort, style and practicality designed for adventurous couples.',
      heroImage: '/drifter/amore/amor.png',
      brochureUrl: '/brochures/AMORE.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'Club Lounge' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminium', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: '2.5kg Top-Load', caption: 'Washing M/C' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '5 × 210W', caption: 'Solar Panel' },
    ],
    specTable: {
      ultra: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Legs x 4', '2 X Battery Boxes'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'postform Benchtops', 'Recessed Mini grill', 'Air conditioner Frame', 'smoke detector'],
        electrical: ['Gree 3500 air conditioner', 'Led Boot Lights', 'External 240 Power point', 'HV Wingard sensor', 'Grey Anderson Plug', '12 Pin Trailer Plug'],
        plumbing: ['Water fillers X 2 Lockable', '224L DOMETIC 3 way Fridge', 'Fridge/Freezer', 'Swift Mini grill', 'Water filter system', 'Thetford Cassette Toilet'],
      },
      terrain: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Step', 'Do-35 Coupling'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'postform Benchtops', 'Queen Bed 1900 x 500mm', 'smoke detector', 'Bottom MountRangehood'],
        electrical: ['3500 Gree air conditioner', 'Led Internal Down lights', 'Led Boot Lights', 'Tv Antenna', 'Bottom mount Rangehood', 'BM-pro Trail safe'],
        plumbing: ['Water fillers X 2 Lockable', '188L DOMETIC 3 way', 'Fridge/Freezer', 'Swift Mini grill', '1 x Elec + 3 x gas', 'White Ceramic Basin'],
      },
      hiker: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', '3200KG 10" Brakes', 'Roller rocker suspension'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'postform Benchtops', 'Recessed Mini grill', '20L Microwave', 'smoke detector'],
        electrical: ['Gree 3500 air conditioner', 'Led Internal Down lights', 'Led Boot Lights', 'External 240 Power point', 'BM-pro Trail safe', 'Grey Anderson Plug'],
        plumbing: ['Water fillers X 2 Lockable', '188L DOMETIC 12v', 'Fridge/Freezer', 'Swift Mini grill', 'Water filter system', 'Flick Mixer Taps'],
      },
    },
    premiumLiving: {
      heading: 'Features For Every Explorer.',
      body: "The Amore 22 boasts a Meranti timber frame, composite aluminium cladding, and checkerplate protection for unbeatable strength. Generous fresh water supply, a 188L fridge, powerful air conditioning and 20L microwave means comfort wherever you go. The spacious rear lounge transforms journeys into luxury escapes. With a fully equipped ensuite, separate shower, 2.5kg top-loader washing machine, and cassette toilet, you'll feel pampered at every destination. The layout promotes relaxation after a day's adventure, with open shelving and recessed lighting adding to its contemporary feel.",
      images: ['/drifter/amore/interior1.png', '/drifter/amore/interior2.png', '/drifter/amore/interior3.png'],
      chips: ['2.5kg Washer', 'Meranti Frame', 'Diesel Heating', 'Separate Shower'],
    },
    floorplans: [
      { title: 'Amore 18.6', desc: 'Compact Luxury 3D', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/AMORE 18.6.png' },
      { title: 'Amore 22.6', desc: 'Spacious Club Lounge', src: '/Amore/Layouts Amore/Copy of AMORE 22.6FT STD.jpg' },
    ],
    cta: {
      kicker: 'Luxury Tourer',
      heading: 'Ready For The Amore 22?',
      body: 'Contact our team to configure the perfect Amore 22 for your touring lifestyle.',
    },
    gallery: {
      exterior: [
        '/Amore/Images/External/Copy of IMG-20250603-WA0069.jpg',
        '/Amore/Images/External/Copy of IMG-20250603-WA0072.jpg',
        '/Amore/Images/External/Copy of IMG-20250603-WA0073.jpg',
        '/Amore/Images/External/Copy of IMG-20250603-WA0075.jpg',
        '/Amore/Images/External/Copy of IMG-20250603-WA0078.jpg',
        '/Amore/Images/External/Copy of IMG-20250603-WA0079.jpg',
        '/Amore/Images/External/Copy of IMG-20250603-WA0080.jpg',
        '/Amore/Images/External/Copy of IMG-20250603-WA0081.jpg',
        '/Amore/Images/External/Copy of IMG-20250603-WA0082.jpg',
        '/Amore/Images/External/Copy of IMG-20250603-WA0083.jpg',
        '/Amore/Images/External/Copy of WhatsApp Image 2025-04-19 at 07.36.26_90a44680.jpg',
      ],
      interior: [
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0049.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0051.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0052.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0053.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0054.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0055.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0056.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0057.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0058.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0059.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0060.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0061.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0062.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0063.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0065.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0067.jpg',
        '/Amore/Images/Internal 2/Copy of IMG-20250603-WA0068.jpg',
      ],
    },
    showMoodBoard: true,
    backLinkHref: '/drifter',
    backLinkLabel: 'Drifter Series',
  },

  // ── ATOM ─────────────────────────────────────────────────────
  {
    seriesSlug: 'atom',
    slug: 'atom',
    name: 'Atom Range',
    status: 'published',
    order: 1,
    hero: {
      kicker: 'Compact Range',
      title: 'Compact.',
      subtitle: 'Atom Caravan',
      body: 'A caravan with sleek design and rugged off-road capability; tailored for couples seeking adventure without compromise. The Atom range comprises three layouts — 17.2ft (agile single-axle compact performer), 17.6ft (touring perfection — the flagship Atom layout, available now), and 17.8ft (the Ultra layout with maximum space efficiency).',
      heroImage: '/rover/atomrover.jpg',
      brochureUrl: '/brochures/ATOM.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'L-Lounge Convertible' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminium', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: 'Wall-mount', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '4 × 210W', caption: 'Solar Panel' },
    ],
    specTable: SPEC_TABLE_EMPTY,
    premiumLiving: {
      heading: 'Innovative Design Solutions.',
      body: "The Atom's interior layout demonstrates masterful space utilisation. It features a queen-size island bed surrounded by overhead lockers and wardrobes. The foldable benchtop and round mirrored vanity add a touch of elegance, making every moment on the road a comfortable experience. The versatile L-lounge configuration provides comfortable daytime seating that converts effortlessly into additional sleeping space when required. Combined with the full ensuite featuring separate shower and toilet facilities, the Atom delivers functionality and comfort typically associated with much larger caravan models.",
      images: ['/rover/atom/Inner A/1.jpg', '/rover/atom/Inner A/2.jpg', '/rover/atom/Inner A/3.jpg'],
      chips: ['Single Axle', 'Island Bed', 'L-Lounge', 'Full Ensuite', '6 Layouts'],
    },
    floorplans: [
      { title: 'Atom 17.2', desc: 'Single Axle Compact', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/ATOM 17.2.png' },
      { title: 'Atom 17.6', desc: 'Touring Perfection', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GTH ATOM 17.6.png' },
      { title: 'Atom 17.8', desc: 'The Ultra Layout', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GTH ATOM 17.8.png' },
    ],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Go Atomic.',
      body: "Contact our team to configure the perfect Atom caravan for your couple's escape.",
    },
    gallery: {
      exterior: [
        '/Atom/Images/External/Copy of IMG_0006.jpg',
        '/Atom/Images/External/Copy of IMG_0008.jpg',
        '/Atom/Images/External/Copy of IMG_0010.jpg',
        '/Atom/Images/External/Copy of IMG_0013.jpg',
        '/Atom/Images/External/Copy of IMG_0015.jpg',
        '/Atom/Images/External/Copy of IMG_0020.jpg',
        '/Atom/Images/External/Copy of IMG_0022.jpg',
        '/Atom/Images/External/Copy of IMG_0025.jpg',
        '/Atom/Images/External/Copy of IMG_0029.jpg',
        '/Atom/Images/External/Copy of IMG_0031.jpg',
        '/Atom/Images/External/Copy of IMG_0036.jpg',
        '/Atom/Images/External/Copy of IMG_0039.jpg',
        '/Atom/Images/External/Copy of IMG_0731.jpg',
        '/Atom/Images/External/Copy of IMG_0735.jpg',
        '/Atom/Images/External/Copy of IMG_0738.jpg',
        '/Atom/Images/External/Copy of IMG_0742.jpg',
        '/Atom/Images/External/Copy of IMG_0746.jpg',
        '/Atom/Images/External/Copy of IMG_0749.jpg',
      ],
      interior: [
        '/Atom/Images/Internal/Copy of IMG_0069.jpg',
        '/Atom/Images/Internal/Copy of IMG_0750.jpg',
        '/Atom/Images/Internal/Copy of IMG_0757.jpg',
        '/Atom/Images/Internal/Copy of IMG_0759.jpg',
        '/Atom/Images/Internal/Copy of IMG_0766.jpg',
        '/Atom/Images/Internal/Copy of IMG_0769.jpg',
        '/Atom/Images/Internal/Copy of IMG_0775.jpg',
        '/Atom/Images/Internal/Copy of IMG_0781.jpg',
        '/Atom/Images/Internal/Copy of IMG_0783.jpg',
        '/Atom/Images/Internal/Copy of IMG_0785.jpg',
        '/Atom/Images/Internal/Copy of IMG_0787.jpg',
      ],
    },
    showMoodBoard: true,
    backLinkHref: '/',
    backLinkLabel: 'The Lineup',
  },
  {
    seriesSlug: 'atom',
    slug: 'atom-17-2',
    name: 'Atom 17.2',
    status: 'published',
    order: 2,
    hero: {
      kicker: 'Compact Variant',
      title: 'Atom',
      subtitle: '17.2FT',
      body: 'The agile single-axle compact performer. A nimble footprint with all the Atom comforts — designed for couples chasing the quickest path from driveway to destination.',
      heroImage: '/rover/atom/Inner A/1.jpg',
      brochureUrl: '/brochures/ATOM.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'L Lounge' },
      { icon: 'fridge', value: '188L', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminium', caption: 'Rivitech Frame' },
      { icon: 'suspension', value: 'Tuffride', caption: 'Independent Suspension' },
      { icon: 'washer', value: '2.5kg Wall mount', caption: 'Washing Machine' },
      { icon: 'battery', value: '1 × 120Ah', caption: 'AGM Battery' },
      { icon: 'solar', value: '1 × 210W', caption: 'Solar Panel' },
    ],
    specTable: SPEC_TABLE_EMPTY,
    premiumLiving: {
      heading: 'Compact Living Refined.',
      body: 'Every centimetre earns its keep. A premium leatherette L-lounge converts into extra sleeping; the kitchen runs a 224L Dometic compressor fridge, recessed grill, and proper benchtop. Soft ambient lighting and full ensuite keep the smallest Atom comfortable on the longest trips.',
      images: ['/rover/atom/Inner A/1.jpg', '/rover/atom/Inner A/2.jpg', '/rover/atom/Inner A/3.jpg'],
      chips: ['Single Axle', 'L-Lounge', 'Full Ensuite', 'Ambient Lighting'],
    },
    floorplans: [
      { title: 'Atom 17.2', desc: 'Agile Single-Axle Compact', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/ATOM 17.2.png' },
    ],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Ready For The Atom 17.2?',
      body: 'Contact our team to configure your Atom 17.2 for your next adventure.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: false,
    backLinkHref: '/atom',
    backLinkLabel: 'Atom Range',
  },
  {
    seriesSlug: 'atom',
    slug: 'atom-17-8',
    name: 'Atom 17.8',
    status: 'published',
    order: 3,
    hero: {
      kicker: 'Ultra Variant',
      title: 'Atom',
      subtitle: '17.8FT',
      body: 'The Ultra layout with maximum space efficiency. The biggest Atom in the range, fitted with the premium hardware list for couples who want the long-haul comforts in a compact-class caravan.',
      heroImage: '/rover/atom/Inner B/1.jpg',
      brochureUrl: '/brochures/ATOM.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Premium Leatherette', caption: 'L-Lounge Convertible' },
      { icon: 'fridge', value: '224L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum', caption: 'Rivitec Frame' },
      { icon: 'suspension', value: 'Tuffride L3', caption: 'Airbag Susp.' },
      { icon: 'washer', value: 'Wall-mount', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 300Ah', caption: 'Lithium' },
      { icon: 'solar', value: '4 × 210W', caption: 'Solar Panel' },
    ],
    specTable: SPEC_TABLE_EMPTY,
    premiumLiving: {
      heading: 'Ultra Layout Maximised.',
      body: 'The Ultra plan stretches the Atom footprint to its maximum efficiency — premium leatherette L-lounge that converts to extra sleeping, 224L Dometic compressor fridge, full ensuite, and the off-grid hardware stack to match: 2× 300Ah lithium, 4× 210W solar, Tuffride L3 airbag suspension.',
      images: ['/rover/atom/Inner B/1.jpg', '/rover/atom/Inner B/2.jpg', '/rover/atom/Inner B/3.jpg'],
      chips: ['Single Axle', 'L-Lounge', 'Full Ensuite', 'Ambient Lighting'],
    },
    floorplans: [
      { title: 'Atom 17.8', desc: 'The Ultra Layout', src: '/3D LAYOUTS 2024/3D LAYOUT NEW UPDATED AUG 2025/GTH ATOM 17.8.png' },
    ],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Ready For The Atom Ultra?',
      body: 'Contact our team to configure your Atom 17.8 for your next adventure.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: false,
    backLinkHref: '/atom',
    backLinkLabel: 'Atom Range',
  },

  // ── HÜTTE ────────────────────────────────────────────────────
  {
    seriesSlug: 'huttle',
    slug: 'huttle',
    name: 'Hütte 14.6',
    status: 'published',
    order: 1,
    hero: {
      kicker: 'Elevated · 14.6 ft',
      title: 'Compact.',
      subtitle: 'The Hütte',
      body: "At just 14.6 ft, the Hütte redefines what's possible in a small footprint — a clever layout, a fully separate ensuite, and a sleek, easy-to-tow design for travellers who refuse to compromise on comfort.",
      heroImage: '/huttle/exterior.jpg',
      brochureUrl: '/brochures/HUTTE.pdf',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Separate Shower', caption: 'Toilet' },
      { icon: 'fridge', value: '188L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum/Celuka', caption: 'Hybrid Framing' },
      { icon: 'suspension', value: 'Shine XT', caption: 'Independent Suspension' },
      { icon: 'washer', value: '2.5kg Wall Mount', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 150Ah', caption: 'Lithium' },
      { icon: 'solar', value: '3 × 200W', caption: 'Solar Panel' },
    ],
    specTable: SPEC_TABLE_EMPTY,
    premiumLiving: {
      heading: 'Premium Living On Wheels.',
      body: 'Warm timber finishes, ambient lighting, and a clever café-style lounge create a cabin that feels generous well beyond its 14.6 ft footprint. Overhead lockers, a full benchtop, and an articulated TV mount keep the space versatile. A fully partitioned ensuite with a dedicated shower stall is a rarity at this length — it gives you the comfort and privacy of a much larger caravan without surrendering the agility that brought you here.',
      images: ['/huttle/interior.jpg', '/huttle/shower.jpg', '/huttle/front.jpg'],
      chips: ['Café Lounge', 'Articulated TV', 'Ambient Lighting', 'Separate Shower'],
    },
    floorplans: [],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Ready For The Hütte?',
      body: 'Contact our team to configure the perfect Hütte 14.6 for your touring lifestyle.',
    },
    gallery: {
      exterior: [
        '/huttle/exterior.jpg',
        '/huttle/exterior-3q.jpg',
        '/huttle/exterior-side.jpg',
        '/huttle/exterior-rear.jpg',
        '/huttle/front.jpg',
        '/huttle/front-2.jpg',
      ],
      interior: [
        '/huttle/interior.jpg',
        '/huttle/interior-front.jpg',
        '/huttle/interior-rear.jpg',
        '/huttle/shower.jpg',
      ],
    },
    showMoodBoard: true,
    backLinkHref: '/',
    backLinkLabel: 'The Lineup',
  },

  // ── ARMADILLO (Elite) ────────────────────────────────────────
  {
    seriesSlug: 'armadillo',
    slug: 'armadillo',
    name: 'Armadillo',
    status: 'published',
    order: 1,
    hero: {
      kicker: 'Flagship Model',
      title: 'Luxurious.',
      subtitle: 'Armadillo',
      body: 'Discover unmatched durability and comfort designed for explorers seeking the ultimate off-road caravan experience. Built tough to take you anywhere with ease.',
      heroImage: '/elite/armadillo.png',
      brochureUrl: '',
      quickStats: [],
    },
    specIcons: [
      { icon: 'inverter', value: '3000W', caption: 'Inverter' },
      { icon: 'lounge', value: 'Separate Shower', caption: 'Toilet' },
      { icon: 'fridge', value: '188L Dometic', caption: 'Compressor Fridge' },
      { icon: 'frame', value: 'Aluminum/Celuka', caption: 'Hybrid Framing' },
      { icon: 'suspension', value: 'Shine XT', caption: 'Independent Suspension' },
      { icon: 'washer', value: '2.5kg Wall Mount', caption: 'Washing Machine' },
      { icon: 'battery', value: '2 × 150Ah', caption: 'Lithium' },
      { icon: 'solar', value: '3 × 200W', caption: 'Solar Panel' },
    ],
    specTable: SPEC_TABLE_EMPTY,
    premiumLiving: {
      heading: 'Adventure-Ready Included.',
      body: "The Armadillo boasts a full aluminium frame, ensuring strength and durability for off-road journeys. Spacious interior with modern conveniences enhances every trip. Off-road suspension and water tanks increase travel independence. The seamless blend of rugged capability and elegant design sets the Armadillo apart. With thoughtful storage solutions and advanced technology onboard, it redefines outdoor comfort. Adventure seekers will appreciate the caravan's resilience and refined interior aesthetics alike.",
      images: ['/elite/interior1.png', '/elite/interior2.png', '/elite/interior3.png'],
      chips: ['188L 3-Way Fridge', 'Rear Club Lounge', 'Queen Bed', 'Diesel Heater'],
    },
    floorplans: [],
    cta: {
      kicker: 'Ultimate Expedition',
      heading: 'Elevate Your Adventures.',
      body: 'Take the first step toward unmatched luxury explorer living. Contact us to configure your Armadillo.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: true,
    backLinkHref: '/elite',
    backLinkLabel: 'Elite Series',
  },
  {
    seriesSlug: 'armadillo',
    slug: 'toy-haulers',
    name: 'Toy Haulers',
    status: 'published',
    order: 2,
    hero: {
      kicker: 'Extreme Gear Range',
      title: 'Toy Haulers.',
      subtitle: '',
      body: 'Engineered for the ultimate outdoor enthusiast. Our Toy Hauler series provides the perfect mobile garage for your motorcycles, ATVs, or bikes without sacrificing luxury living.',
      heroImage: '/roverbg.png',
      brochureUrl: '',
      quickStats: [],
    },
    specIcons: [],
    specTable: SPEC_TABLE_EMPTY,
    premiumLiving: {
      heading: 'Bring Your Adventures.',
      body: 'Why choose between your gear and your comfort? The Hike RV Toy Hauler series is built tough to carry your toys and stylish enough to be your home away from home. Featuring heavy-duty ramps, secure tie-downs, and modular interiors.',
      images: [],
      chips: ['Heavy Duty Ramp', 'Secure Tie-downs', 'Modular Interior'],
    },
    floorplans: [],
    cta: {
      kicker: 'Ready to Load Up?',
      heading: 'Your Gear, Anywhere.',
      body: 'Contact our specialists to configure your HIKE X series Toy Hauler. Customized layouts available to fit your specific toys and lifestyle.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: true,
    backLinkHref: '/',
    backLinkLabel: 'Back to Home',
  },

  // ── ECO ──────────────────────────────────────────────────────
  {
    seriesSlug: 'eco',
    slug: 'eco-186',
    name: 'Eco 18.6',
    status: 'published',
    order: 1,
    hero: {
      kicker: 'Eco Collection',
      title: 'Eco 18.6FT',
      subtitle: '',
      body: 'Engineered for high-performance efficiency and sustainable adventure, the Eco series offers multiple layouts to suit every voyager.',
      heroImage: '/rover/ecorover.png',
      brochureUrl: '',
      quickStats: [],
    },
    specIcons: [],
    specTable: {
      ultra: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Legs x 4', '2 X Battery Boxes'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'Postform Benchtops', 'Recessed Mini grill', 'Air conditioner Frame', 'Smoke detector'],
        electrical: ['LED Internal Down lights', 'LED Boot Lights', 'External 240 Power point', 'HV Wingard sensor', 'Grey Anderson Plug', '12 Pin Trailer Plug'],
        plumbing: ['Water fillers X 2 Lockable', '224L DOMETIC 3 way Fridge', 'Fridge/Freezer', 'Swift Mini grill', 'Water filter system', 'Thetford Cassette Toilet'],
      },
      terrain: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', 'Drop Step', 'Do-35 Coupling'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'Postform Benchtops', 'Queen Bed 1900 x 500mm', 'Smoke detector', 'Bottom Mount Rangehood'],
        electrical: ['Belair 3400 air conditioner', 'LED Internal Down lights', 'LED Boot Lights', 'External 240 Power point', 'Bottom mount Rangehood', 'BM-pro Trail safe'],
        plumbing: ['Water fillers X 2 Lockable', '188L DOMETIC 3 way', 'Fridge/Freezer', 'Swift Mini grill', '1 x Elec + 3 x gas', 'White Ceramic Basin'],
      },
      hiker: {
        chassis: ['Silver shine chassis', '6" Chassis', '2" Chassis Raiser', '6" Extended A-frame', '2800KG 12" Brakes', '8" Jockey Wheels'],
        furniture: ['White stipple Furniture', 'Front robe port Holes', 'Postform Benchtops', 'Recessed Mini grill', '20L Microwave', 'Smoke detector'],
        electrical: ['Belair 3400 air conditioner', 'LED Internal Down lights', 'LED Boot Lights', 'External 240 Power point', 'BM-pro Trail safe', 'Grey Anderson Plug'],
        plumbing: ['Water fillers X 2 Lockable', '188L DOMETIC 12v', 'Fridge/Freezer', 'Swift Mini grill', '1 x Elec + 3 x gas', 'Water filter system'],
      },
    },
    premiumLiving: {
      heading: 'Built For Adventure.',
      body: "Whether it's the compact Eco 18.6, rugged Drifter Series, or luxurious Elite models, each range has stylish interiors, smart storage, and durable construction tailored to both on-road and off-grid adventures. Choose true freedom and luxury with Hike RV Caravans. Every model offers ultimate comfort, innovative yet practical design, and reliable performance, ensuring you enjoy every twist, turn, and stop on your next adventure.",
      images: ['/rover/eco/interior1.png', '/rover/eco/interior2.png', '/rover/eco/interior3.png'],
      chips: [],
    },
    floorplans: [
      { title: 'Eco 18.6', desc: 'Optimized Single Axle', src: '/3D LAYOUTS 2024/18.6 FT ECO.jpg' },
    ],
    cta: {
      kicker: 'Your Adventure Starts Here',
      heading: 'Go Eco.',
      body: 'Contact our team to configure the perfect Eco 18.6 for your next adventure.',
    },
    gallery: { exterior: [], interior: [] },
    showMoodBoard: true,
    backLinkHref: '/eco',
    backLinkLabel: 'Eco Series',
  },
];
